# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Larry's blog"
email: larrysu1115@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  吾生也有涯，而知也無涯。
  以有涯隨無涯，殆已；已而為知者，殆而已矣。
   - 養生主
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.sws9f.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  larrysu1115

# Build settings
markdown            : kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge

